export const fontsLibrary = [
  {
    colors: ['#000000', '#FFFFFF', '#FF5733'],
    gradientColors: [
      ['#FF5733', '#FFC300'],
      ['#FF5733', '#C70039'],
      ['#FF5733', '#900C3F'],
      ['#FF5733', '#581845'],
      ['#FF5733', '#DAF7A6'],
      ['#FF5733', '#FFC300'],
      ['#FF5733', '#FF5733'],
      ['#FF5733', '#C70039'],
      ['#FF5733', '#900C3F'],
      ['#FF5733', '#581845'],
    ],
    description: [
      'A bold, geometric sans-serif font perfect for impactful messages.',
      'Clean, modern, and highly versatile for a variety of designs.',
    ],
    mood: 'Confident and Energetic',
    nuance: 'Bold and Professional',
    atmosphere: 'Modern and Structured',
    possiblePairs: [
      {
        heading: 'Montserrat-Bold',
        bodyText: 'OpenSans-Regular',
        useThisFor: 'Modern and minimalist social media posts or banners.',
      },
      {
        heading: 'Montserrat-SemiBold',
        bodyText: 'Lato-Light',
        useThisFor: 'Clean and professional branding or website headers.',
      },
    ],
  },
  {
    colors: ['#333333', '#FFFFFF', '#FF69B4'],
    gradientColors: [
      ['#FF69B4', '#FFC0CB'],
      ['#FF69B4', '#FF1493'],
      ['#FF69B4', '#DB7093'],
      ['#FF69B4', '#C71585'],
      ['#FF69B4', '#FFB6C1'],
      ['#FF69B4', '#FF69B4'],
      ['#FF69B4', '#FFC0CB'],
      ['#FF69B4', '#FF1493'],
      ['#FF69B4', '#DB7093'],
      ['#FF69B4', '#C71585'],
    ],
    description: [
      'A clean and elegant sans-serif font with a touch of sophistication.',
      'Perfect for modern and stylish social media posts.',
    ],
    mood: 'Elegant and Modern',
    nuance: 'Sophisticated and Clean',
    atmosphere: 'Trendy and Sleek',
    possiblePairs: [
      {
        heading: 'Raleway-Bold',
        bodyText: 'OpenSans-Regular',
        useThisFor: 'Stylish Instagram posts or blog headers.',
      },
      {
        heading: 'Raleway-SemiBold',
        bodyText: 'Lato-Light',
        useThisFor: 'Minimalist and professional branding.',
      },
    ],
  },
  {
    colors: ['#000000', '#FFFFFF', '#FF6347'],
    gradientColors: [
      ['#FF6347', '#FF4500'],
      ['#FF6347', '#FF7F50'],
      ['#FF6347', '#FF8C00'],
      ['#FF6347', '#FFA07A'],
      ['#FF6347', '#FFD700'],
      ['#FF6347', '#FF6347'],
      ['#FF6347', '#FF4500'],
      ['#FF6347', '#FF7F50'],
      ['#FF6347', '#FF8C00'],
      ['#FF6347', '#FFA07A'],
    ],
    description: [
      'A condensed sans-serif font with a bold and impactful style.',
      'Ideal for headlines and attention-grabbing social media designs.',
    ],
    mood: 'Bold and Dynamic',
    nuance: 'Strong and Modern',
    atmosphere: 'High-Impact and Structured',
    possiblePairs: [
      {
        heading: 'Oswald-Bold',
        bodyText: 'Roboto-Regular',
        useThisFor: 'Bold headlines for social media banners.',
      },
      {
        heading: 'Oswald-Medium',
        bodyText: 'OpenSans-Light',
        useThisFor: 'Dynamic and modern Instagram posts.',
      },
    ],
  },
  {
    colors: ['#444444', '#FFFFFF', '#FFD700'],
    gradientColors: [
      ['#FFD700', '#FFA500'],
      ['#FFD700', '#FF8C00'],
      ['#FFD700', '#FF4500'],
      ['#FFD700', '#FF6347'],
      ['#FFD700', '#FF7F50'],
      ['#FFD700', '#FFD700'],
      ['#FFD700', '#FFA500'],
      ['#FFD700', '#FF8C00'],
      ['#FFD700', '#FF4500'],
      ['#FFD700', '#FF6347'],
    ],
    description: [
      'A rounded sans-serif font with a friendly and approachable style.',
      'Perfect for modern and casual social media posts.',
    ],
    mood: 'Friendly and Approachable',
    nuance: 'Soft and Welcoming',
    atmosphere: 'Casual and Modern',
    possiblePairs: [
      {
        heading: 'Nunito-Bold',
        bodyText: 'OpenSans-Regular',
        useThisFor: 'Friendly and casual Instagram posts.',
      },
      {
        heading: 'Nunito-SemiBold',
        bodyText: 'Lato-Light',
        useThisFor: 'Modern and approachable branding.',
      },
    ],
  },
  {
    colors: ['#000000', '#FFFFFF', '#8B0000'],
    gradientColors: [
      ['#8B0000', '#FF4500'],
      ['#8B0000', '#DC143C'],
      ['#8B0000', '#B22222'],
      ['#8B0000', '#A52A2A'],
      ['#8B0000', '#800000'],
      ['#8B0000', '#8B0000'],
      ['#8B0000', '#FF4500'],
      ['#8B0000', '#DC143C'],
      ['#8B0000', '#B22222'],
      ['#8B0000', '#A52A2A'],
    ],
    description: [
      'An elegant serif font with a classic and luxurious feel.',
      'Perfect for high-end branding and sophisticated social media posts.',
    ],
    mood: 'Elegant and Luxurious',
    nuance: 'Classic and Refined',
    atmosphere: 'Sophisticated and Timeless',
    possiblePairs: [
      {
        heading: 'PlayfairDisplay-Bold',
        bodyText: 'OpenSans-Regular',
        useThisFor: 'Elegant Instagram captions or blog headers.',
      },
      {
        heading: 'PlayfairDisplay-Medium',
        bodyText: 'Lato-Light',
        useThisFor: 'Sophisticated and timeless branding.',
      },
    ],
  },
  {
    colors: ['#000000', '#FFFFFF', '#FF4500'],
    gradientColors: [
      ['#FF4500', '#FFD700'],
      ['#FF4500', '#FF6347'],
      ['#FF4500', '#FF8C00'],
      ['#FF4500', '#FFA07A'],
      ['#FF4500', '#FFB6C1'],
      ['#FF4500', '#FF4500'],
      ['#FF4500', '#FFD700'],
      ['#FF4500', '#FF6347'],
      ['#FF4500', '#FF8C00'],
      ['#FF4500', '#FFA07A'],
    ],
    description: [
      'A versatile slab-serif font with a modern and professional feel.',
      'Perfect for bold headlines and impactful social media posts.',
    ],
    mood: 'Professional and Bold',
    nuance: 'Modern and Structured',
    atmosphere: 'Confident and Reliable',
    possiblePairs: [
      {
        heading: 'RobotoSlab-Bold',
        bodyText: 'OpenSans-Regular',
        useThisFor: 'Professional and bold social media banners.',
      },
      {
        heading: 'RobotoSlab-Medium',
        bodyText: 'Lato-Light',
        useThisFor: 'Modern and structured branding.',
      },
    ],
  },
  {
    colors: ['#000000', '#FFFFFF', '#8B0000'],
    gradientColors: [
      ['#8B0000', '#FF4500'],
      ['#8B0000', '#DC143C'],
      ['#8B0000', '#B22222'],
      ['#8B0000', '#A52A2A'],
      ['#8B0000', '#800000'],
      ['#8B0000', '#8B0000'],
      ['#8B0000', '#FF4500'],
      ['#8B0000', '#DC143C'],
      ['#8B0000', '#B22222'],
      ['#8B0000', '#A52A2A'],
    ],
    description: [
      'A serif font with a warm and sophisticated feel.',
      'Perfect for elegant and timeless social media posts.',
    ],
    mood: 'Elegant and Warm',
    nuance: 'Classic and Refined',
    atmosphere: 'Sophisticated and Timeless',
    possiblePairs: [
      {
        heading: 'Lora-Bold',
        bodyText: 'OpenSans-Regular',
        useThisFor: 'Elegant Instagram captions or blog headers.',
      },
      {
        heading: 'Lora-Medium',
        bodyText: 'Lato-Light',
        useThisFor: 'Sophisticated and timeless branding.',
      },
    ],
  },
  {
    colors: ['#222222', '#FFFFFF', '#00CED1'],
    gradientColors: [
      ['#00CED1', '#20B2AA'],
      ['#00CED1', '#5F9EA0'],
      ['#00CED1', '#4682B4'],
      ['#00CED1', '#B0C4DE'],
      ['#00CED1', '#ADD8E6'],
      ['#00CED1', '#00CED1'],
      ['#00CED1', '#20B2AA'],
      ['#00CED1', '#5F9EA0'],
      ['#00CED1', '#4682B4'],
      ['#00CED1', '#B0C4DE'],
    ],
    description: [
      'A clean and modern sans-serif font with a friendly aesthetic.',
      'Perfect for approachable and professional social media posts.',
    ],
    mood: 'Friendly and Professional',
    nuance: 'Clean and Welcoming',
    atmosphere: 'Casual and Modern',
    possiblePairs: [
      {
        heading: 'FiraSans-SemiBold',
        bodyText: 'Roboto-Regular',
        useThisFor: 'Friendly and professional Instagram captions.',
      },
      {
        heading: 'FiraSans-Medium',
        bodyText: 'OpenSans-Light',
        useThisFor: 'Approachable and modern branding.',
      },
    ],
  },
]
